services:
  api-message:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: api-message-development:latest
    container_name: api-message-development
    platform: ${SERVER_PLATFORM}
    ports:
      - "3001:3000"
    environment: # This configuration can override the settings in the Dockerfile.
      - PORT=3000
    volumes:
      - ../../logs:/app/logs
    command: ["npm", "run", "start:dev"] # Also can override the settings in the Dockerfile.
